"1": 
  
  stage: "1" 
  name: "Tìm hiểu đề bài"
  description: |
    Xác định ẩn số và dữ liệu (giả thuyết – kết luận).
    Nhận diện yêu cầu: tìm hay chứng minh gì?
    (Nếu bài toán đơn giản, có thể bỏ qua phân tích chi tiết.)
  tasks:
    - "Liệt kê ẩn số, dữ kiện đầu bài và mục tiêu cần đạt."
    - "Khi hoàn thành, chuyển sang giai đoạn 'Lập kế hoạch'."
  goals: 
    - "Xác định đây là bài toán xét tính đơn điệu của hàm số bậc nhất trên bậc nhất."

"2": 
  stage: "2"
  name: "Lập kế hoạch"
  description: |
    Đề xuất phương pháp giải tổng quát mà không thực hiện chi tiết.
    Nhìn bài toán dưới nhiều góc độ: kiến thức, công cụ, đánh giá tính khả thi.
  tasks:
    - "Phân tích và nhận xét ít nhất một phương pháp khả thi."
    - "Khi thỏa thuận, chuyển sang giai đoạn 'Thực hiện giải'."
  goals: 
    - "Thống nhất dùng đạo hàm để xét tính đơn điệu và lập bảng biến thiên."

"3": 
  stage: "3"
  name: "Thực hiện giải"
  description: |
    Triển khai các bước giải đã thống nhất, kèm đánh giá kết quả từng bước.
  tasks:
    - "Tính đạo hàm f'(x) và xét dấu từng khoảng." 
    - "Lập bảng biến thiên."                      
    - "Sau khi hoàn tất, chuyển sang giai đoạn 'Kết luận'."
  goals:
    - "Tính đúng đạo hàm và xét dấu."
    - "Nhận diện khoảng đồng biến, nghịch biến qua bảng biến thiên."

"4": 
  stage: "4"
  name: "Kết luận"
  description: |
    Tóm tắt quy trình giải và đánh giá hiệu quả phương pháp.
    Rút ra nguyên tắc chung cho dạng toán.
  tasks:
    - "Tóm tắt các bước chính."
    - "Đánh giá ưu nhược điểm."
    - "Khái quát nguyên tắc giải:" 
    - |                          
      1. Xác định tập xác định D.
      2. Tính f'(x), tìm điểm khảo sát.
      3. Xét dấu và lập bảng biến thiên.
      4. Kết luận khoảng đồng/ nghịch biến.
  goals: 
    - "Hoàn thiện kết luận và kết thúc thảo luận."