"1":
  stage: "1"
  name: |
    Tìm hiểu đề bài: "Bùa chú đơn điệu"
  description: |
    Chào mừng các phù thủy và pháp sư tương lai! Hôm nay, chúng ta sẽ sử dụng kiến thức toán học để giải một "bùa chú đơn điệu" liên quan đến sự biến thiên của hàm số.
    Trước tiên, hãy đọc kỹ "lời nguyền" (bài toán) mà chúng ta cần giải.
    Bài toán của chúng ta là: Xét tính đơn điệu của hàm số $f(x) = -x^3 + 3x - 2$.
  tasks:
    - id: "1.1"
      description: |
        Theo con, yêu cầu chính của "lời nguyền" này là gì?
        Chúng ta cần tìm gì hoặc chứng minh điều gì về hàm số $f(x) = -x^3 + 3x - 2$?
    - id: "1.2"
      description: |
        "Lời nguyền" này cho chúng ta biết những thông tin gì quan trọng?
        Hãy liệt kê những dữ kiện hoặc đặc điểm nổi bật của hàm số đã cho.
        Ví dụ, nó là hàm đa thức bậc mấy?
  goals:
    - "Hiểu rõ yêu cầu của bài toán (xét tính đơn điệu)."
    - "Xác định được hàm số cần khảo sát."
"2":
  stage: "2"
  name: "Lập kế hoạch giải bài: Chuẩn bị cho 'bùa chú'."
  description: |
    Tuyệt vời! Bây giờ, chúng ta cần chuẩn bị cho "bùa chú" bằng cách vạch ra kế hoạch chi tiết.
    Đây là những bước quan trọng để giải quyết bài toán về tính đơn điệu của hàm số.
  tasks:
    - id: "2.1"
      description: |
        Bước đầu tiên trong việc "khảo sát bùa chú" này là gì? (Gợi ý: Hàm số có nghĩa ở đâu?)
        Chúng ta cần xác định điều kiện tồn tại của hàm số, hay còn gọi là gì nhỉ?
    - id: "2.2"
      description: |
        Sau khi xác định "lãnh thổ" của hàm số, chúng ta cần tìm "sức mạnh" của nó.
        Vậy bước tiếp theo là gì? (Gợi ý: Liên quan đến sự thay đổi của hàm số)
    - id: "2.3"
      description: |
        Khi đã có "sức mạnh" (đạo hàm), chúng ta cần giải mã nó.
        Bước tiếp theo là gì để biết hàm số tăng hay giảm?
    - id: "2.4"
      description: |
        Để vẽ bản đồ chi tiết về sự biến thiên của hàm số, chúng ta cần tìm thêm thông tin gì?
        (Gợi ý: giá trị tại điểm đặc biệt và ở vô cùng)
    - id: "2.5"
      description: |
        Cuối cùng, chúng ta sẽ trình bày tất cả thông tin thu thập được dưới dạng nào để dễ dàng nhìn thấy sự biến thiên của hàm số?
  goals:
    - "Xác định được các bước cần thiết để giải bài toán."
    - "Hiểu rõ thứ tự thực hiện các bước."
"3":
  stage: "3"
  name: "Thực hiện giải bài: Thi triển 'bùa chú'."
  description: |
    Đã đến lúc thi triển "bùa chú"! Chúng ta sẽ thực hiện từng bước trong kế hoạch để giải quyết "lời nguyền" đơn điệu này.
    Hãy tập trung và cẩn thận trong từng bước tính toán nhé.
  tasks:
    - id: "3.1"
      description: |
        Đầu tiên, hãy xác định "lãnh thổ" của hàm số $f(x) = -x^3 + 3x - 2$.
        Hàm số này có điều kiện gì không? Nó xác định trên khoảng nào?
    - id: "3.2"
      description: |
        Tiếp theo, chúng ta cần tìm "sức mạnh" của hàm số.
        Hãy tính đạo hàm $f'(x)$ của hàm số $f(x) = -x^3 + 3x - 2$.
        Nhớ lại các quy tắc tính đạo hàm cơ bản nhé!
    - id: "3.3"
      description: |
        Bây giờ, hãy tìm các điểm mà "sức mạnh" bằng không, tức là giải phương trình $f'(x) = 0$.
        Các giá trị $x$ này có ý nghĩa gì trong việc xét tính đơn điệu của hàm số?
    - id: "3.4"
      description: |
        Xác định dấu của $f'(x)$ trên các khoảng giữa các nghiệm vừa tìm được.
        $f'(x)$ mang dấu dương nghĩa là gì? Âm nghĩa là gì?
    - id: "3.5"
      description: |
        Tính giá trị của hàm số $f(x)$ tại các điểm mà $f'(x) = 0$.
        $f(-1) = ?$ và $f(1) = ?$
    - id: "3.6"
      description: |
        Tính giới hạn của $f(x)$ khi $x$ tiến tới $+\infty$ và $-\infty$.
        $\lim_{x \to +\infty} f(x) = ?$
        $\lim_{x \to -\infty} f(x) = ?$
    - id: "3.7"
      description: |
        Dựa vào tất cả thông tin thu thập được, hãy vẽ bảng biến thiên của hàm số $f(x)$.
        Bảng biến thiên sẽ cho chúng ta thấy rõ sự tăng giảm của hàm số trên các khoảng khác nhau.
  goals:
    - "Tính toán chính xác đạo hàm và các giá trị liên quan."
    - "Xác định đúng dấu của đạo hàm trên các khoảng."
    - "Vẽ đúng bảng biến thiên của hàm số."
"4":
  stage: "4"
  name: "Kết luận và Đánh giá: Giải mã 'bùa chú'."
  description: |
    Chúc mừng! Chúng ta đã thành công thi triển "bùa chú" và thu thập đủ thông tin.
    Bây giờ là lúc đưa ra kết luận cuối cùng về tính đơn điệu của hàm số.
  tasks:
    - id: "4.1"
      description: |
        Dựa vào bảng biến thiên, hãy cho biết hàm số $f(x)$ đồng biến trên khoảng nào?
        Ở đó, đạo hàm $f'(x)$ mang dấu gì?
    - id: "4.2"
      description: |
        Dựa vào bảng biến thiên, hãy cho biết hàm số $f(x)$ nghịch biến trên những khoảng nào?
        Ở đó, đạo hàm $f'(x)$ mang dấu gì?
    - id: "4.3"
      description: |
        Vậy, theo con, chúng ta có thể kết luận gì về tính đơn điệu của hàm số $f(x) = -x^3 + 3x - 2$?
        Hãy tóm tắt lại kết quả chúng ta vừa tìm được.
  goals:
    - "Nắm vững khái niệm về tính đơn điệu của hàm số."
    - "Biết cách sử dụng đạo hàm để xét tính đơn điệu."
    - "Đưa ra kết luận chính xác về tính đơn điệu của hàm số."