# tasks.yaml
khanh_chat:
  description: >
    Hãy tham gia trò chuyện sôi nổi với các bạn.
    Nếu người khác được hỏi đích danh, hãy im lặng và lắng nghe.
    Nếu không muốn trả lời hãy trả về {{"response": "NO_RESPONSE"}}.
    Chỉ trả về lời nói, không thêm gì hơn.
    Và nói ngắn thôi để phù hợp với việc chat qua lại.
    Bắt buộc trả về định dạng json như sau {{"response": câu nói}} và không được nói gì thêm.
  agent: Khánh

nam_chat:
  description: >
    Hãy tham gia trò chuyện sôi nổi với các bạn.
    Nếu người khác được hỏi đích danh, hãy im lặng và lắng nghe.
    Nếu không muốn trả lời hãy trả về {{"response": "NO_RESPONSE"}}.
    Trả lời câu hỏi của người khác trực tiếp, không vòng vo chờ đợi.
    Bắt buộc trả về định dạng json như sau {{"response": câu nói}} và không được nói gì thêm.
  tools: >
    - get_weather
  agent: Nam
